version: '3'

services:
    auth:
        image: jupytercloud/webserver
        env_file:
            - secret.env
        environment:
            - COURSE=${COURSE}
            - PORT=${PORT}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - SECRET_KEY=${JWT_SECRET_KEY}

        volumes:
            - ./accounts.yaml:/etc/jupytercloud/accounts.yaml:ro
            - ${HOST_DATA_VOLUME}/${COURSE}:/jupytercloud_data:ro
            - ./logo.png:/jupytercloud-auth-service/app/static/logo.png
            - /var/run/docker.sock:/var/run/docker.sock
    jupyterhub:
        image: jupytercloud/hub
        env_file:
            - secret.env
        environment:
            - COURSE=${COURSE}
            - PORT=${PORT}
            - LOCAL_NOTEBOOK_IMAGE=${COURSE_NOTEBOOK_IMAGE}
            - DOCKER_NETWORK_NAME=${COURSE}_default
            - HOST_DATA_VOLUME=${HOST_DATA_VOLUME}
            - NB_UID=${NB_UID}
            - NB_GID=${NB_GID}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - SINGLEUSER_CPUS=${SINGLEUSER_CPUS}
            - SINGLEUSER_MEM_LIMIT=${SINGLEUSER_MEM_LIMIT}
            - DISABLE_CULLING
        volumes:
            - ./accounts.yaml:/etc/jupytercloud/accounts.yaml:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ${HOST_DATA_VOLUME}/${COURSE}:/jupytercloud_data
            - ./logo.png:/srv/jupyterhub/venv/share/jupyterhub/static/images/jupyterhub-80.png
            - ./logo.png:/srv/jupyterhub/venv/share/jupyterhub/static/images/jupyterhub.png
    proxy:
        image: jupytercloud/proxy
        environment:
            - COURSE=${COURSE}
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
